# Exercise 3 - Smith Waterman simplified implementation

Implement algorithm that will fill in score table for two sequences

Let’s test it on previous example:
 - Sequence1 - "attcagct"
 - Sequence2 - "atcagtct”
 
 
Scoring:
 - indel_score = -2
 - match_score = 2
 - mismatch_score = -1





In [1]:
import numpy

In [3]:
sequence1 = "atcagtct"
sequence2 = "attcagct"

indel_score = -2
match_score = 2
mismatch_score = -1

sequence1 = "-" + sequence1
sequence2 = "-" + sequence2

In [4]:
#inicijalizacija matrice nulama
score_table = numpy.zeros((len(sequence1), len(sequence2)))

In [5]:
score_table

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
def calculate_possibilities(score_table, i, j, sequence1, sequence2):
    values = []
    #diagonal comming to the cell
    if sequence1[i] == sequence2[j]:
        values.append(score_table[i-1][j-1] + match_score)
    else:
        values.append(score_table[i-1][j-1] + mismatch_score)
    # from upper cell or left cell
    values.append(score_table[i][j-1] + indel_score)
    values.append(score_table[i-1][j] + indel_score)
    #if all values are lower than 0
    values.append(0)
    return values

In [7]:
for i in range(1,len(sequence1)):
    for j in range(1,len(sequence2)):
        score_table[i][j] = max(calculate_possibilities(score_table, i, j, sequence1, sequence2))

In [8]:
print(score_table)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  2.  0.  0.  0.]
 [ 0.  0.  4.  2.  0.  0.  1.  0.  2.]
 [ 0.  0.  2.  3.  4.  2.  0.  3.  1.]
 [ 0.  2.  0.  1.  2.  6.  4.  2.  2.]
 [ 0.  0.  1.  0.  0.  4.  8.  6.  4.]
 [ 0.  0.  2.  3.  1.  2.  6.  7.  8.]
 [ 0.  0.  0.  1.  5.  3.  4.  8.  6.]
 [ 0.  0.  2.  2.  3.  4.  2.  6. 10.]]
